Fix up a parse error
The non-generic ParseQueryAdapter class fails when results are read due
to a cast error:

    java.lang.ClassCastException: com.parse.ParseObject cannot be cast to org.ashanet.typedef.Event
    	at org.ashanet.adapter.EventListAdapter.getItemView(EventListAdapter.java:20)
    	at com.parse.ParseQueryAdapter.getView(ParseQueryAdapter.java:546)
    	at android.widget.AbsListView.obtainView(AbsListView.java:2033)
    	at android.widget.ListView.makeAndAddView(ListView.java:1772)
    	at android.widget.ListView.fillDown(ListView.java:672)
    	at android.widget.ListView.fillFromTop(ListView.java:732)
        ...

This is because the type parameter was not registered.  Register it in
the Application class.